tracing:
  jaeger:
    localAgentHostPort: jaeger:6831

http:
  routers:
    api:
      rule: "Host(`dev.schneesporttage.ml`) && PathPrefix(`/api`)"
      service: api
    frontend:
      rule: "Host(`dev.schneesporttage.ml`)"
      service: frontend
  services:
    api:
      loadBalancer:
        servers:
        - url: https://host.docker.internal:7268
    frontend:
      loadBalancer:
        servers:
        - url: http://host.docker.internal:3000